general.import = ["colors/matugen.toml"]

[cursor.style]
blinking = "Always"
shape = "Beam"

# [cursor.vi_mode_style]
# height = 0.1
# shape = "Block"

[env]
TERM = "xterm-256color"
TERM_PROGRAM = "alacritty"

[font]
size = 10

[font.normal]
family = "Source Code Pro"


[scrolling]
# auto_scroll = true
history = 2000

[selection]
save_to_clipboard = true

[terminal.shell]
program = "/usr/bin/fish"

[window]
dynamic_title = false
blur = true
opacity = 0.75
title = "Alacritty"

[window.padding]
x = 10
y = 10

[window.dimensions]
columns = 150
lines = 35

[terminal]
